
#title: Audio Puzzle
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: Babaloga/AudioPuzzle
name: Audio Puzzle
title: null

# Build settings
layouts_dir: layouts
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

